---
deployment:
  tasks:
    - export DEPLOYPATH=/home/agroskyt/public_html/
    - mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R test $DEPLOYPATH
