---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/agroskyt/public_html/test.agroskytech.co.za/
    - mkdir -p $DEPLOY_PATH
    - /bin/cp .htaccess $DEPLOY_PATH
    - /bin/cp 404.html $DEPLOY_PATH
    - /bin/cp -R assets $DEPLOY_PATH
    - /bin/cp -R ./test/* $DEPLOY_PATH
