name: 🚀 Deploy website on push
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4.2.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./public_html/"
          server-dir: "./public_html/"
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.gitignore
            **/.idea/**
            **/node_modules/**
